# -*- coding: utf-8 -*-
"""automate_Suryani.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwewJ7AHcInVbM4xnRvsrkWN-h5gHZCW
"""

import os
import pandas as pd
import numpy as np
import argparse
import logging
import sys
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

# Konfigurasi Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Membuat heart_raw.csv dari datase Kaggle
if not os.path.exists('heart_raw.csv'):
  try:
    df_raw = pd.read_csv('/content/sample_data/heart_disease_uci.csv')
    df_raw.to_csv('heart_raw.csv', index=False)
    logging.info(f"heart_raw.csv dibuat dari upload manual. Shape: {df_raw.shape}")
  except FileNotFoundError:
    logging.error("File heart_disease_uci.csv tidak ditemukan")
    sys.exit(1)
  except Exception as e:
    logging.error("File heart_disease_uci.csv tidak ditemukan")
    sys.exit(1)
else:
  logging.info("heart_raw.csv sudah ada")

# Fungsi Preprocessing
def run_preprocessing(input_path):
  try:
      logging.info(f"Memulai preprocessing untuk file: {input_path}")

      # Step 1 - Load Data
      df = pd.read_csv(input_path)
      df_clean = df.copy()
      logging.info(f"Data berhasil dimuat. Shape: {df_clean.shape} ")

      # Step 2 - Hapus kolom yang tidak relevan untuk modeling
      drop_cols = ['id', 'dataset']
      df_clean = df_clean.drop(columns=[c for c in drop_cols if c in df_clean.columns])
      logging.info(f"Kolom {drop_cols} dihapus.")

      # Step 3 - Binarize Target: num > 0 --> 1 (ada penyakit), 0 --> 0 (tidak ada)
      df_clean['target'] = (df_clean['num'] > 0).astype(int)
      df_clean = df_clean.drop(columns=['num'])
      logging.info(f"Target 'num' di-binarize menjadi kolom 'target'.")

      # Step 4 - Hapus Duplikat
      before = len(df_clean)
      df_clean = df_clean.drop_duplicates()
      logging.info(f"Duplikat dihapus: {before - len(df_clean)} baris.")

      # Step 5 - Imputasi Missing Values
      numerical_features = ['age', 'trestbps', 'chol', 'thalch', 'oldpeak', 'ca']
      # Kolom binary (True/False) --> Label Encode
      binary_features   = ['sex', 'fbs', 'exang']
      # Kolom Kategorikal string --> One-Hot Encode
      ohe_features      = ['cp', 'restecg', 'slope', 'thal']

      num_imputer = SimpleImputer(strategy='median')
      df_clean[numerical_features] = num_imputer.fit_transform(df_clean[numerical_features])

      cat_imputer = SimpleImputer(strategy='most_frequent')
      df_clean[binary_features] = cat_imputer.fit_transform(df_clean[binary_features])
      df_clean[ohe_features] = cat_imputer.fit_transform(df_clean[ohe_features])
      logging.info("Imputasi missing values selesai.")

      # Step 6 - Penanganan Outlier (IQR Clipping)
      for col in numerical_features:
          Q1 = df_clean[col].quantile(0.25)
          Q3 = df_clean[col].quantile(0.75)
          IQR = Q3 - Q1
          df_clean[col] = df_clean[col].clip(lower=Q1 - 1.5 * IQR, upper=Q3 + 1.5 * IQR)
      logging.info("Outlier ditangani dengan IQR clipping.")

      # Step 7 - Label Encoding untuk fitur binary
      le = LabelEncoder()
      for col in binary_features:
          df_clean[col] = le.fit_transform(df_clean[col].astype(str))
      logging.info(f"Label Encoding untuk: {binary_features}.")

      # Step 8 - One-Hot Encoding untuk fitur kategorikal
      for col in ohe_features:
          df_clean[col] = df_clean[col].astype(str)
      df_encoded = pd.get_dummies(df_clean, columns=ohe_features, prefix=ohe_features)
      logging.info(f"One-Hot Encoding untuk: {ohe_features}.")

      # Step 9 - Standarisasi Fitur Numerik
      X = df_encoded.drop(columns=['target'])
      y = df_encoded['target']
      scaler = StandardScaler()
      X[numerical_features] = scaler.fit_transform(X[numerical_features])
      logging.info("Standarisasi fitur numerik selesai.")

      # Step 10 - Train-Test Split (80:20, Stratified)
      X_train, X_test, y_train, y_test = train_test_split(
          X, y, test_size=0.2, random_state=42, stratify=y
      )
      logging.info(f"Train-Test Split: X_train={X_train.shape}, X_test={X_test.shape}")

      # Step 11 - Simpan Hasil
      train_df = pd.concat([X_train, y_train], axis=1)
      test_df = pd.concat([X_test, y_test], axis=1)

      train_df.to_csv('heart_preprocessing_train.csv', index=False)
      test_df.to_csv('heart_preprocessing_test.csv', index=False)
      logging.info("Preprocessing selesai.")
      logging.info(f" heart_preprocessing_train.csv : {train_df.shape}")
      logging.info(f" heart_preprocessing_test.csv : {test_df.shape}")

  except FileNotFoundError:
      logging.error(f"File tidak ditemukan: {input_path}")
  except Exception as e:
      logging.error(f"Terjadi kesalahan: {e}")
      raise

# Entry Point
def is_notebook():
    try:
        shell = get_ipython().__class__.__name__
        return shell in ('ZMQInteractiveShell', 'Shell')
    except NameError:
        return False

if is_notebook():
    run_preprocessing('heart_raw.csv')
else:
    parser = argparse.ArgumentParser(description="Automated Preprocessing Script")
    parser.add_argument('--input', type=str, default='heart_raw.csv', help='Path to raw dataset')
    args = parser.parse_args()
    run_preprocessing(args.input)
